#!/bin/sh

TDIR=/data/connectbook/tutorials
TTAG=osg
cd

list_tuts () {
	(
		cd "$TDIR"
		for d in *; do
			if [ -d "$d" -a -f "$d/.info" ]; then
				info=$(head -1 "$d/.info")
				printf "%-18.18s %s\n" "$d" "$info"
			fi
		done
	)
}

tut_info () {
	if [ -f "$TDIR/$1/.info" ]; then
		cat "$TDIR/$1/.info"
	fi
}

findnew () {
	base="$1"
	i=1
	while [ $i -lt 500 ]; do
		if [ ! -e "$base.$i" ]; then
			echo "$base.$i"
			return
		fi
		i=$(($i + 1))
	done
}

info=false
tutorial="$1"

if [ -z "$tutorial" -o "$tutorial" = "-h" -o "$tutorial" = "--help" ]; then
	echo >&2 "usage: tutorial name-of-tutorial"
	echo >&2 "       tutorial info name-of-tutorial"
	echo
	echo "Available tutorials:"
	list_tuts
	exit 2
fi

if [ "$tutorial" = "info" ]; then
	info=true
	tutorial="$2"
fi

if [ "$2" = "info" ]; then
	info=true
fi

if [ ! -d "$TDIR/$tutorial" ]; then
	echo >&2 "No tutorial named '$tutorial' exists.  Available tutorials:"
	list_tuts
	exit 10
fi

if $info; then
	tut_info "$tutorial"
	exit 0
fi

if [ -e "$TTAG-$tutorial" ]; then
	newname=$(findnew "$TTAG-$tutorial")
	echo >&2 "NOTE: '$TTAG-$tutorial' already exists in your home directory."
	echo >&2 "Renaming it to '$newname'."
	mv "$TTAG-$tutorial" "$newname"
fi

cp -pr "$TDIR/$tutorial" "$TTAG-$tutorial"
cd "$TTAG-$tutorial"

if [ -f ./.setup.sh ]; then
	bash .setup.sh
fi

cat .info
echo
echo "Tutorial '$tutorial' is set up.  To begin:"
echo "     cd ~/$TTAG-$tutorial"
exit 0
